site_name: Asian Languge Learning Guide
site_url: https://spazztl.github.io/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: blue
  
  font:
   # text: Merriweather Sans
    code: Red Hat Mono
  features:
  - navigation.tabs
  
  
nav:
  #- Home: home.md
  - Korean:
      - 'Getting Started': korean.md
  - Japanese: japanese.md
  - Chinese: chinese.md

markdown_extensions:
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
    
      baselevel: "3"
      toc_depth: "3"
      
  - pymdownx.superfences
  - pymdownx.tabbed: 
      alternate_style: true 