site_name: Ultimate Korean Guide
site_url: https://spazztl.github.io/
extra_css:
  - css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css # <-- Add this line!

theme:
  name: material
  custom_dir: theme/overrides
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: blue
  
  font:
    text: Roboto
    code: Red Hat Mono
  features:
  - navigation.tabs
  
  
nav:
  #- Home: home.md
  - Korean:
      - 'Getting Started': korean.md
      - 'Resources': koreanresources.md
  - Japanese: japanese.md
  - Chinese: chinese.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
      baselevel: 2
      toc_depth: 4
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true